services:
  managed-notebook:
    image: lexaraprime/embra_connect_notebook:1.0
    # For [LOCAL] development
    # image: embra_connect_notebook:1.0 
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=user
    volumes:
      - /home/jovyan



# Credentials
# JUPYTER_TOKEN -> user

# Mount directory
# ./ -> Represents the current directory of the user's terminal