apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbt
  template:
    metadata:
      labels:
        app: dbt
    spec:
      containers:
      - name: dbt
        image: lexaraprime/embra_connect_dbt_service
        ports:
        - containerPort: 3000
