version: "3.3"

services:
  # Web-Client server
  server:
    build:
      context: ./server
    ports:
      - 5500:5500

  # DBT service
  dbt_service:
    build:
      context: ./services/dbt
    ports:
      - 3000:3000

  editor:
    image: lexaraprime/embra_connect_editor:1.0
    volumes:
      - /config
    ports:
      - 8080:8080
    restart: unless-stopped
