version: "3.3"

services:
  ec_firewall:
    image: irfanghat/ec_firewall:latest
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - ec_network
    environment:
      INFISICAL_UNIVERSAL_CLIENT_ID: ${INFISICAL_UNIVERSAL_CLIENT_ID}
      INFISICAL_UNIVERSAL_CLIENT_SECRET: ${INFISICAL_UNIVERSAL_CLIENT_SECRET}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      INFISICAL_SITE_URL: ${INFISICAL_SITE_URL}

  ec_gateway:
    image: irfanghat/ec_gateway:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - ec_network
    environment:
      INFISICAL_UNIVERSAL_CLIENT_ID: ${INFISICAL_UNIVERSAL_CLIENT_ID}
      INFISICAL_UNIVERSAL_CLIENT_SECRET: ${INFISICAL_UNIVERSAL_CLIENT_SECRET}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      INFISICAL_SITE_URL: ${INFISICAL_SITE_URL}

  ec_access_control:
    image: irfanghat/ec_access_control:latest
    restart: unless-stopped
    depends_on:
      - ec_gateway
    ports:
      - "8800:8800"
    networks:
      - ec_network
    environment:
      INFISICAL_UNIVERSAL_CLIENT_ID: ${INFISICAL_UNIVERSAL_CLIENT_ID}
      INFISICAL_UNIVERSAL_CLIENT_SECRET: ${INFISICAL_UNIVERSAL_CLIENT_SECRET}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      INFISICAL_SITE_URL: ${INFISICAL_SITE_URL}

  ec_connect_ide:
    image: irfanghat/ec_connect_ide:latest
    restart: unless-stopped
    depends_on:
      - ec_access_control
    ports:
      - "7000:7000"
    networks:
      - ec_network
    environment:
      INFISICAL_UNIVERSAL_CLIENT_ID: ${INFISICAL_UNIVERSAL_CLIENT_ID}
      INFISICAL_UNIVERSAL_CLIENT_SECRET: ${INFISICAL_UNIVERSAL_CLIENT_SECRET}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      INFISICAL_SITE_URL: ${INFISICAL_SITE_URL}

  ec_client:
    image: irfanghat/ec_client:latest
    restart: unless-stopped
    depends_on:
      - ec_connect_ide
    ports:
      - "8000:8000"
    networks:
      - ec_network
    environment:
      INFISICAL_UNIVERSAL_CLIENT_ID: ${INFISICAL_UNIVERSAL_CLIENT_ID}
      INFISICAL_UNIVERSAL_CLIENT_SECRET: ${INFISICAL_UNIVERSAL_CLIENT_SECRET}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      INFISICAL_SITE_URL: ${INFISICAL_SITE_URL}

networks:
  ec_network:
    driver: bridge
