[package]
name = "embra_connect_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "9.3.0"
rocket = "0.5.1"
tokio = { version = "1.39.3", features = ["full"] }

